/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_INVENTORY: 'add-inventory',
  DISPENSE: 'dispense',
  DISPENSE_LOG: 'dispense-log',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  ABOUT_US: 'about',
  STATUS: 'status',
  STATUS_NOTIFICATION: 'status-notification',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sigin-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  MED_STATUS: 'med-status',
  VACCINE_STATUS: 'vaccine-status',
  SUPPLY_STATUS: 'supply-status',
  MANAGE_DROPDOWNS: 'manage-dropdowns',
};
